title = "Texas Gitleaks Config"

# Extend the base (this) configuration. When you extend a configuration
# the base rules take precedence over the extended rules. I.e., if there are
# duplicate rules in both the base configuration and the extended configuration
# the base rules will override the extended rules.
# Another thing to know with extending configurations is you can chain together
# multiple configuration files to a depth of 2. Allowlist arrays are appended
# and can contain duplicates.
# useDefault and path can NOT be used at the same time. Choose one.
[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
id = "pemFile"
description = "Remove .pem files"
path = '.*\.pem'

[[rules]]
id = "keyFile"
description = "Remove .key files"
path = '.*\.key'

[[rules]]
id = "crtFile"
description = "Remove .crt files"
path = '.*\.crt'

[[rules]]
id = "cerFile"
description = "Remove .cer files"
path = '.*\.cer'

[[rules]]
id = "stateFile"
description = "Remove .state files"
path = '.*\.state'

[[rules]]
id = "tfstateFile"
description = "Remove .tfstate files"
path = '.*\.tfstate'

[[rules]]
id = "backupFile"
description = "Remove .backup files"
path = '.*\.backup'

[[rules]]
id = "dsStoreFile"
description = "Remove .ds_store files"
path = '.*\.ds_store'

[[rules]]
id = "ovpnFile"
description = "Remove .ovpn files"
path = '.*\.ovpn'

[[rules]]
id = "awsCredentialsFile"
description = "Remove aws/credentials files"
path = '.*\aws/credentials'

[[rules]]
id = "openVpnRetryFile"
description = "Remove .openvpn.retry files"
path = '.*\.openvpn.retry'

[allowlist]
description = "Allow example AWS key"
paths = [
  '.gitleaks.toml',
  '.gitallowed',
  'stacks/instance-lifecycle/instance_terminator_v2/.*',
  '.*/docker/docs/ipv6.md'
]
regexTarget = "line"
regexes = [
  'key_name\s=\s".*"',
  'KeyIdentifier\s=\srfc',
  '(0|10|127|168|169|172|192|255)\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(/\d{1,3})?',
  '\d\.\d\.\d\.\d',
  'Key\s*=\s*var\.',

  # https://github.com/NHSDigital/software-engineering-quality-framework/blob/main/tools/nhsd-git-secrets/nhsd-rules-deny.txt

  '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8,12}/[a-zA-Z0-9_]{24}''',
  '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}''',
  '''ghp_[0-9a-zA-Z]{36}''',
  '''gho_[0-9a-zA-Z]{36}''',
  # '''(ghu|ghs)_[0-9a-zA-Z]{36}''',
  # '''ghr_[0-9a-zA-Z]{76}''',
  # '''xox[baprs]-([0-9a-zA-Z]{10,48})?''',
  '''AIza[0-9A-Za-z\\-_]{35}''',
  '''"type": "service_account"''',
  '''[a-z]{2}-[a-z-]*-[1,2,3]\.rds\.amazonaws\.com''',
  '''rds\.[a-z]{2}-[a-z-]*-[1,2,3]\.amazonaws\.com''',
  '''dynamodb\.[a-z]{2}-[a-z-]*-[1,2,3]\.amazonaws\.com''',
  '''[a-z]{2}-[a-z-]*-[1,2,3]\.es\.amazonaws\.com''',
  '''[a-z]*[1-3]\.cache\.amazonaws\.com''',
  '''-----BEGIN[[:blank:]]CERTIFICATE-----''',
  '''[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}''',
  '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}''',
  '''(CLIENT|client|Client)(_|\s)(SECRET|secret|Secret)\s*(:|=>|=)\s*("|')?(\{)?[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\})?("|\')?''',
  '''password\s*(=|:)\s*.+''',
  # Non standard \X is not recognised as a regex char
  '''\btoken:.+.+\d\b''',
  '''[0-9]{12}'''
]

stopwords = [ ]
