name: Launch self hosted runner
description: Launches a self hosted runner
inputs:
  environment:
    required: true
    description: The environment to deploy to
  region:
    required: false
    default: eu-west-2
    description: The AWS region being deployed to
  runner-label:
    required: true
    description: The label of the GitHub runner
  aws-account-id:
    description: The AWS account id being deployed to
runs:
  using: composite
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/texas-github
        role-session-name: github-deploy-env
        aws-region: ${{ inputs.region }}
        output-credentials: true
    - name: Create runner
      shell: bash
      run: ./.github/scripts/runEcsTask.sh "${{ inputs.runner-label }}"
