apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - REPLACE_WITH_AWS_REGIONa
            topologyKey: "kubernetes.io/zone"
      containers:
      - name: jmslave
        image: 730319765130.dkr.ecr.eu-west-2.amazonaws.com/texas/jmeter-slave:5.4.1-log4j2-patch
        imagePullPolicy: Always
        ports:
        - containerPort: 1099
        - containerPort: 50000
        resources:
          limits: #May need to increase Limits dependent on intensity of Load Test
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 20m
            memory: 350Mi

